version: "3.9"


# Caddy (running as a NixOS service) proxies public traffic to these.

services:
  # Nextcloud All-in-One: only the launcher container here; it will manage its own internal stack.
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    # Bind only to loopback; Caddy will proxy from the public internet.
    ports:
      - "127.0.0.1:8080:8080"   # AIO admin interface and initial setup
      - "127.0.0.1:11000:11000" # Nextcloud application port (proxied by Caddy)
      # Optional: AIO can also run services on additional ports; keep them loopback-bound and add Caddy routes as needed.
    volumes:
      # Use a host bind mount so data lives under your chosen path
      - /vol/nextcloud/aio-config:/mnt/docker-aio-config
      # Docker socket required for AIO to manage its internal container stack
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - AIO_DISABLE_BACKUP_SECTION=true
      # Set your domain so AIO configures trusted proxies correctly
      - APACHE_IP_BINDING=127.0.0.1
      # If running behind Caddy with HTTPS, AIO can auto-detect forwarded headers.
    networks:
      - backend

  theyoungartistsclub-db:
    image: mariadb
    container_name: theyoungartistsclub-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /vol/artists/theyoungartistsclub-db:/var/lib/mysql
    # Secrets for DB credentials (expects MYSQL_* vars)
    env_file:
      - /vol/secrets/tyac.env
    networks:
      - backend


  allergy-db:
    image: mariadb
    container_name: allergy-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /vol/allergy/allergy-db:/var/lib/mysql
    # Secrets for DB credentials (expects MYSQL_* vars)
    env_file:
      - /vol/secrets/allergy.env
    networks:
      - backend


  theyoungartistsclub:
    image: wordpress
    container_name: theyoungartistsclub
    restart: always
    depends_on:
      - theyoungartistsclub-db
    ports:
      - "127.0.0.1:8002:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # Secrets for app DB config (expects WORDPRESS_DB_* vars)
    env_file:
      - /vol/secrets/tyac.env
    environment:
      - WORDPRESS_DB_HOST=theyoungartistsclub-db:3306
    volumes:
      - /vol/artists/theyoungartistsclub:/var/www/html
      - /vol/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - backend

  allergy:
    image: wordpress
    container_name: allergy
    restart: always
    depends_on:
      - allergy-db
    ports:
      - "127.0.0.1:8003:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # Secrets for app DB config (expects WORDPRESS_DB_* vars)
    env_file:
      - /vol/secrets/allergy.env
    environment:
      - WORDPRESS_DB_HOST=allergy-db:3306
    volumes:
      - /vol/allergy/allergy:/var/www/html
      - /vol/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - backend

networks:
  backend:
    driver: bridge
